#### Numpy nos permite trabajar facilmente con arrays multidimencionales 

In [32]:
import numpy as np

#### AXIS: cada una de las dimensiones del array, es decir, los ejes (x,y en caso de ser bidimensional).

#### LENGTH: El numero de valores que contine una dimension del array.

#### INDEX: La posicion que ocupa un valor determinado dentro del array (tener en cuenta que siempre empiezan desde 0).

#### VALUE: El valor de un indice concreto

#### RANK: cuantas dimensiones (axis) contiene un array.

#### SIZE: la cantidad de elementos que contiene el array (el resultado de columnas X filas).

#### SHAPE: el listado de las diferentes dimensiones (axis) con su longitud, EJ: 8rows x 4cols

#### NOTA: el () representa al tipo de dato tuple, o tupla, un array que no se puede modificar y es solo de lectura


#### Inciar un array de 0s con la shape que querramos

In [33]:
np.zeros((4,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

#### Iniciar un array con la forma que querramos y el valor que deseemos

In [28]:
np.full((3,5), 8)

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

#### Inicar un array con valores random (floats, decimales)

In [29]:
np.random.rand(4,8)

array([[0.07964518, 0.10769566, 0.998658  , 0.8163015 , 0.2719888 ,
        0.78694498, 0.22303317, 0.8937193 ],
       [0.91310177, 0.54172041, 0.77016821, 0.754283  , 0.92698497,
        0.34749264, 0.33271295, 0.73186732],
       [0.47831799, 0.50135383, 0.97199673, 0.0789226 , 0.0045919 ,
        0.09132332, 0.38086996, 0.29793025],
       [0.02286721, 0.87349138, 0.81538648, 0.46732801, 0.36602575,
        0.58296871, 0.55350805, 0.03362152]])

#### Inicar una array con valores enteros random, indicando el valor minimo (inclusivo), maximo (exclusivo) y el shape

In [30]:
my_array = np.random.randint(0, 10, (3,5))
print(my_array)

[[7 7 2 0 5]
 [6 2 3 2 6]
 [8 5 0 3 0]]


#### Cambiar la forma de un array 
#### NOTA1: deben coincidir y ser coherentes
#### NOTA2: esto funciona por referencia, es decir, el segundo dependera del primero

In [17]:
my_reshaped_array = np.reshape(my_array, (5,3))
print(my_reshaped_array)

[[9 3 2]
 [4 3 4]
 [9 5 7]
 [2 8 1]
 [2 0 3]]


#### Convertir una list de py en un array de np

In [18]:
np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

#### Generar un array con un numero minimo, maximo y el rango

In [22]:
my_rank_array = np.linspace(0, 10, 32)

#### Conocer la shape del array
#### Conoer el size del array

In [24]:
print(my_rank_array.shape)
print(my_rank_array.size)

(32,)
32


#### Realizar sumas de arrays, tambien se pueden realizar el resto de operaciones aritmeticas 

In [25]:
my_array1 = np.array([1,2,3])
my_array2 = np.array([2,4,6])

print(my_array1)
print(my_array2)
print(my_array1 + my_array2)

[1 2 3]
[2 4 6]
[3 6 9]


#### NOTA: en caso de que las formas o rangos no coincidan, np duplicara el ultimo valor ya sea en longitud o dimension para ajustarlo y poder realizar la operacion

#### Obtener la media de los valores del array

In [26]:
my_array1.mean()

np.float64(2.0)

#### Sumatoria de todos los elementos

In [27]:
my_array1.sum()

np.int64(6)

#### El valor minimo dentro del array

In [30]:
my_array1.min()

np.int64(1)

#### El valor maximo dentro del array

In [31]:
my_array1.max()

np.int64(3)

#### Acceder a un elemento de un array

In [34]:
print(my_array1[0])
print(my_array1[1])
print(my_array1[2])

1
2
3


In [47]:
array = np.array([[1,2],[3,4],[5,6]])

print(array[0,1])
print(array.shape)

2
(3, 2)


#### Acceder a partes especificas del array, (se accede a las primeras 2 filas)

In [ ]:
print(array[0:2])

[[1 2]
 [3 4]
 [5 6]]


#### Acceder desde la primera posicion hasta el final (eso indica el segundo ":")

In [45]:
print(array[0::])

[[1 2]
 [3 4]
 [5 6]]


#### Modificar posiciones

In [46]:
array[0,1] = 8
print(array)

[[1 8]
 [3 4]
 [5 6]]


#### Envolver todo un array en una unica posicion

In [48]:
print(array.ravel())

[1 2 3 4 5 6]
